
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdbvolume
  labels:
    type: gce-pd
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany    
  gcePersistentDisk:
    pdName: influxdbdisk
    fsType: ext4
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdbclaim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanavolume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: grafanadisk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanaclaim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi